### PR TITLE
Catalog Match High-Fidelity + Additional Filter Functionality

### LINKED ISSUE #41: Catalog Match High-Fidelity + Additional Filter Functionality
## Instructions
- By now, the core functionality of the Catalog should be mostly complete. Now that we also have the high-fidelity design, we can style the Catalog to match the provided design
- Since the Catalog is already decently styled, we’re also adding some additional functionality to this task under the request of the designers (who have now added some features that weren’t in the original version)
- We’d like to allow the user to select multiple filters in a single category (e.g. both Fall and Winter for season)
- We’d like to add a button to the Catalog allowing the user to unselect all of the filters, rather than having to manually unselect each filter

## Notes
- We highly recommend meeting with Vy to get an overview of the design for the Catalog!
- There is minor backend work that needs to be done allow for multiple filter selection in the `GET /catalog` route. Please make a new branch off of dev to work on these changes in the backend.

## Acceptance Criteria
- The design of the Catalog matches the high-fidelity design
- The user can select multiple filters in a single category, and the Catalog responds accordingly
- The user can click a button to remove all of the currently selected filters

## Resources
- [Catalog High Fidelity Design](https://www.figma.com/file/CmrgQbRKVLJWVhSzXxAdad/Low-High-Fidelity?type=design&node-id=761-4191&mode=design&t=8k4nXWspIhlHHe24-4)
- [Current Catalog Frontend](https://github.com/ctc-uci/aiss-frontend/blob/dev/src/pages/Catalog/Catalog.jsx)
- [Catalog Backend Routes](https://github.com/ctc-uci/aiss-backend/blob/dev/routes/catalog.js)

### PR DESCRIPTION
**Pull request by ctc-devops**
Authors:
 ### What does this PR contain?
- [X] Updated catalog to hi-fi design
image

- [X] Extract page fetching logic from footer to page-level component
  - Refactoring the fetch data to the page-level component reduces the likelihood of starting infinite fetches, especially with added state changes with the multi-filter functionality.
```jsx
  const fetchTableData = useCallback(async () => {
    console.log('Fetching Catalog');

    const params = {
      title: searchTerm,
      limit: pageSize,
      page: currentPage,
      ...Object.assign(
        {},
        ...Object.entries(values).map(([k, v]) => {
          return { [k]: v.join(',') };
        }),
      ),
    };


    const { data } = await NPOBackend.get('/catalog', {
      params: params,
    });
    const { count, events: tableData } = data;


    setTableData(tableData);
    setTotalRowCount(Number(count[0].count));
  }, [currentPage, pageSize, searchTerm, values]);


```
[View file](https://github.com/ctc-uci/aiss-frontend/blob/f05903d3097cfadff76b43a73ee723df99c05b93/src/pages/Catalog/Catalog.jsx#L79C1-L103C1)

- [X] Added multiple filter functionality
image

- [X] Clear Filter button will clear all active filters

 ### How did you test these changes?
 ### Attach images (if applicable)
 Closes #41

### CODE REVIEW

**Comment by michellelin1** [comment]
@seancfong i'm not sure if you were already planning on implementing this, but when the user changes the filter can you set the pagination page back to 0? other than that this looks great!! 😍

**Comment by seancfong** [comment]
> @seancfong i'm not sure if you were already planning on implementing this, but when the user changes the filter can you set the pagination page back to 0? other than that this looks great!! 😍

@michellelin1 Sure, I can get that in real quick

**Comment by seancfong** [comment]
@michellelin1 Added [96aac3e](https://github.com/ctc-uci/aiss-frontend/pull/57/commits/96aac3e3e7d51f3f9ec6a812189db233d645bd01) for pagination filter fix

**Review by michellelin1 — APPROVED** [review]
Looks really good!! Also thanks for moving things to separate components!

**Pull request merged**
